export const Errors = {
    CONNECTION_LOST: 'CONNECTION_LOST',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
    AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
};

export const Warnings = {
    SOMETHING_IS_GOING_WRONG: 'SOMETHING_IS_GOING_WRONG',
    DELETE_YOURSELF_PLEASE: 'DELETE_YOURSELF_PLEASE',
};
